### PR TITLE
Add limit to number of blocks

### LINKED ISSUE #92: Add limitation for number of Blockly blocks
Some challenges require this. For now just on Blockly side.

Later we can think of integration with arena/challenge selection

### PR DESCRIPTION
**Pull request by ido-ran**
Fix #92 by allow challange config to specify the number of blocks allowed
to be used. This should help students to identify the are on the wrong
path but it seems like a clear feedback of how many blocks are allowed
is required as blockly simply turn all blocks into "disabled" without
clear explanation why that is.

### CODE REVIEW

**Comment by JamesWP** [comment]
Great start! I think there needs to be some on screen display for the limit, the blockly interface isnt very informative about why you cant select any more blocks. maybe some counter on screen when you approach the limit, this way there is some place to put a reason.

**Comment by ido-ran** [comment]
I've converted this PR to draft because we will need to remove the limits as I'm not sure they are correct.

**Comment by ido-ran** [comment]
I have add the ability to specify if the limit is hard or soft and also more descriptive messages about the number of blocks.
Please see lesion 1 challenge A which has max 6 soft limit and challenge B which has 6 hard limit.
Try to use more blocks then expected in the soft limit.

You can still load a program with more than the allowed limit, even when the limit is hard.
I'm not sure if there is a point in blocking that.

**Comment by JamesWP** [comment]
Works great! I think this is in a place we can land it, there's a chance to improve the looks but that can wait IMO. (I think we could wrap that text in one of those box things with the drop shadow. )

**Pull request merged**
